sudo: false
language: python
cache: pip
services:
  - mongodb
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7 # https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
      dist: xenial
      sudo: true
install:
  - pip install -U pip setuptools
  - pip install tox-travis
  - pip install codecov
  - if [[ $TRAVIS_PYTHON_VERSION != 3.4 ]]; then pip install pre-commit; fi
script:
  - tox
  - if [[ $TRAVIS_PYTHON_VERSION != 3.4 ]]; then pre-commit run --all-files; fi
after_success:
  - codecov
before_script:
  - mongo admin --eval 'db.createUser({user:"root",pwd:"example",roles:[{role:"root",db:"admin"}]});'
